apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-shared-storage
  labels:
    type: local
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.30.10
    path: "/home/ansible/.kubetmp"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-shared-storage-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi